### ISSUE TITLE
 New version error！

### ISSUE THREAD

**Issue by miniknife88** [niceboygithub/AqaraM1SM2fw#11]
Hassos
Homeassistant version: core-2021.7.2

log:
`2021-07-13 21:14:35 ERROR (Thread-17) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.9/threading.py", line 892, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
self.loop_forever(retry_first_connection=True)
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
rc = self.loop(timeout, max_packets)
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1181, in loop
rc = self.loop_read(max_packets)
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1572, in loop_read
rc = self._packet_read()
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
rc = self._packet_handle()
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
return self._handle_publish()
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
self._handle_on_message(message)
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
self.on_message(self, self._userdata, message)
File "/config/custom_components/aqara_gateway/core/gateway.py", line 428, in on_message
self._process_message(payload)
File "/config/custom_components/aqara_gateway/core/gateway.py", line 619, in _process_message
handler(payload)
File "/config/custom_components/aqara_gateway/light.py", line 148, in update
self._hs = color_util.color_RGB_to_hs(*rgb)
TypeError: color_RGB_to_hs() takes 3 positional arguments but 5 were given`

**Comment by niceboygithub** [comment]
I do not have such device on hand.
Can you help to test these code in light.py?

```
                rgb = color_util.rgb_hex_to_rgb_list(value)
                if len(rgb) > 3:
                    self._white = rgb.pop()
                if len(rgb) > 3:
                    self._brightness = rgb.pop()
                self._hs = color_util.color_RGB_to_hs(*rgb)
```
